### ISSUE TITLE
ImportError: No module named 'convnet_drawer'

### ISSUE THREAD

**Issue by gsk1692** [yu4u/convnet-drawer#13]
Getting import error after installing via pip... Can anyone please help?

**Comment by yu4u** [comment]
How did you install via pip?
Please add project root to PYTHONPATH.

**Comment by gsk1692** [comment]
I did just pip install (as given in the repository readme)
Adding to PYTHONPATH also is required?

**Comment by yu4u** [comment]
Yes

**Comment by gsk1692** [comment]
OK. My mistake! Closing issue.... Thanks!
